### ISSUE TITLE
Plugin automatically self-disables

### ISSUE THREAD

**Issue by Grievous07** [ryandw11/CustomStructures#35]
05.04 01:27:20 [Server] ERROR [CustomStructures] Error: The schematic file for demo does not exist!
05.04 01:27:20 [Server] ERROR [CustomStructures] For assistance please contact Ryandw11 on spigot.
05.04 01:27:20 [Server] ERROR [CustomStructures] The plugin will now disable it self.
05.04 01:27:20 [Server] INFO [CustomStructures] Disabling CustomStructures v1.3.3

My server is spigot 1.12.2. Hosted by PebbleHost.

This happens every time that I restart the server. I've already tried uninstalling and reinstalling the plugin but that doesn't seem to help it much. If anybody would be able to help me, that'd be much appreciated. Just let me know whatever I can do to be helpful and I will gladly send it to you.

**Comment by Iniquit** [comment]
Hey! So that error message is just telling you that there's no WorldEdit schematic file named "demo.schem" in your `CustomStructures/schematics` folder. The plugin is looking for one because the default config.yml includes a structure that uses "demo.schem."

If you add a schematic file named demo.schem ([such as this one](https://github.com/ryandw11/CustomStructures/files/4433612/schematic.zip)) to that schematics folder, CustomStructures will be able to find a schematic file to use for that example structure, and the plugin should start normally.

Hope that helps!

**Comment by Grievous07** [comment]
![image](https://user-images.githubusercontent.com/18214761/78811727-4fdb8d80-7998-11ea-9cf4-9961d4c2e01f.png)
As u can see, I put a demo.schematic file into the Custom Structures -> Schematics folder. But it still has the same problem. Should I somehow copy the schematic.demo file's contents and paste it in the file of "Put_Schematics_In_Here"?

**Comment by Grievous07** [comment]
NVM got it to work. 
Though if you don't mind me bothering you for longer. How do I make it that the custom structures only spawn in specific worlds? I'm running multiverse.

**Comment by Grievous07** [comment]
THank you very much for your help, I'm relatively certain I got it to work.

**Comment by ryandw11** [comment]
Issue resolved in 1.4.3.
